apiVersion: v1
data:
  dragent.yaml: |
    ### Agent tags
    # tags: linux:ubuntu,dept:dev,local:nyc

    #### Sysdig Software related config ####

    # Sysdig collector address
    collector: collector-static.sysdigcloud.com

    # Collector TCP port
    collector_port: 6443

    # Whether collector accepts ssl/TLS
    ssl: true

    # collector certificate validation
    ssl_verify_certificate: true

    # Sysdig Secure
    security:
        enabled: true

    #######################################
    # new_k8s: true
    # k8s_cluster_name: production
kind: ConfigMap
metadata:
  creationTimestamp: "2019-10-24T07:31:13Z"
  name: sysdig-agent
  namespace: sysdig-agent
  resourceVersion: "270119"
  selfLink: /api/v1/namespaces/sysdig-agent/configmaps/sysdig-agent
  uid: 41beb771-f630-11e9-8458-52fdfc072182
