apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: "2019-10-11T22:29:53Z"
  finalizers:
  - kubernetes.io/pvc-protection
  labels:
    app: mysql
  name: mysql-pv-claim
  namespace: kubeflow
  resourceVersion: "446518"
  selfLink: /api/v1/namespaces/kubeflow/persistentvolumeclaims/mysql-pv-claim
  uid: a53a6889-ec76-11e9-859a-52fdfc072182
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  volumeMode: Filesystem
